# Generated by Django 4.0.2 on 2022-02-26 10:34

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(validators=[tasks.models.validate_string_not_empty]),
        ),
    ]
