# Generated by Django 4.0.2 on 2022-02-26 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(validators=[django.core.validators.MinValueValidator]),
        ),
    ]
